export const NOUN_COUNT = 10; // Number of nouns the client can choose from
export const VERB_COUNT = 0; // Number of verbs the client can choose from
export const NOUN_LIMIT = 1; // Limit on how many nouns the client can select
export const VERB_LIMIT = 0; // Limit on how many verbs the client can select
export const RANDOM_NOUN_COUNT = 2; // Number of nouns selected if client selects none
export const RANDOM_VERB_COUNT = 0; // Number of verbs selected if client selects none
export const NOUNS = [ // Pool of nouns
  'book',
  'phone',
  'river',
  'mountain',
  'chair',
  'pencil',
  'computer',
  'school',
  'bird',
  'cat',
  'guitar',
  'bottle',
  'ocean',
  'train',
  'pizza',
  'window',
  'door',
  'garden',
  'city',
  'bridge',
  'cloud',
  'camera',
  'flower',
  'clock',
  'table',
  'shoe',
  'forest',
  'planet',
  'candle',
  'cup'
];
export const VERBS = [ // Pool of verbs
  'sing',
  'dance',
  'cook',
  'paint',
  'drive',
  'read',
  'listen',
  'climb',
  'laugh',
  'cry',
  'draw',
  'write',
  'sleep',
  'eat',
  'drink',
  'play',
  'build',
  'break',
  'fix',
  'watch',
  'talk',
  'smile',
  'fly',
  'walk',
  'sit',
  'stand',
  'throw',
  'catch',
  'think',
  'hug'
];
